
name: Docker Image CI

on:
	push:
    branches: [ "main" ]
	pull_request:
    branches: [ "main" ]

jobs:
	build:
  	runs-on: ubuntu-latest
  	environment: production
  	env:
    	DOCKER_IMAGE_NAME: my-site
    	DOCKER_IMAGE_TAG: ${{ github.sha }}
		steps:
    	- name: Checkout code
        uses: actions/checkout@v2
    	- name: Login to Docker Hub
        uses: docker/login-action@v1
      	with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    	- name: Build Docker image
        uses: docker/build-push-action@v2
        with:
					context: .
        	push: true
        	tags: ${{ secrets.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
    	- name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
        	host: ${{ secrets.SERVER_IP }}
					username: ${{ secrets.SERVER_USERNAME }}
					key: ${{ secrets.SERVER_ACCESS_TOKEN }}
					script: |
            docker pull ${{ secrets.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
            docker tag ${{ secrets.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} ${{ secrets.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}:latest
            cd ${{ vars.DEVOPS_DOCKER_WORKSPACE }}
            docker-compose up -d --force-recreate --build ${{ env.DOCKER_IMAGE_NAME }}